package land.cookie.cordova.plugin.bluebirdreader;

public class BarcodeTypes {
    public static final int UNKNOWN = -1;
    public static final int UPC_A = 1;
    public static final int UPC_E = 2;
    public static final int UPC_E1 = 3;
    public static final int EAN8 = 4;
    public static final int EAN13 = 5;
    public static final int BOOKLAND = 6;
    public static final int CODE39 = 8;
    public static final int CODE93 = 9;
    public static final int CODE128 = 10;
    public static final int INTERLEAVED2OF5 = 11;
    public static final int CODABAR = 12;
    public static final int CODE11 = 13;
    public static final int MSI = 14;
    public static final int PDF417 = 16;
    public static final int ISBT128 = 17;
    public static final int MATRIX2OF5 = 19;
    public static final int DATAMATRIX = 20;
    public static final int MAXICODE = 21;
    public static final int AZTECCODE = 22;
    public static final int MICROPDF = 23;
    public static final int QRCODE = 24;
    public static final int TRIOPTIC_CODE = 25;
    public static final int DISCRETE2OF5 = 26;
    public static final int USPS4CB = 27;
    public static final int AUSTRALIA_POST = 28;
    public static final int UK_POST = 29;
    public static final int CHINESE_POST = 30;
    public static final int JAPANESE_POST = 31;
    public static final int NETHERLANDS_POST = 32;
    public static final int KOREAN_POST = 33;
    public static final int US_POSTNET = 34;
    public static final int US_PLANET = 35;
    public static final int EAN_TRANSMIT_ISSN = 43;
    public static final int CODE39_FULL_ASCII = 51;
    public static final int GS1_LIMITED = 74;
    public static final int ISBT128_CONCATENATION = 76;
    public static final int COMPOSITE_TLC_39 = 85;
    public static final int COUPON_REPORT = 95;
    public static final int GS1_DATABAR_EXPANDED = 101;
    public static final int UPU_FICS_POSTAL = 104;
    public static final int MICROQR = 113;
    public static final int CODE49 = 114;
    public static final int OCR = 115;
    public static final int CANADIAN_POST = 116;
    public static final int CODE32 = 119;
    public static final int CODE16K = 123;
    public static final int HANXIN = 134;
    public static final int IATA = 136;
    public static final int EAN128 = 137;
    public static final int UPC_D = 138;
    public static final int GS1_DATABAR = 139;
    public static final int SCANLET = 140;
    public static final int CUECODE = 141;
    public static final int SIGNATURE_CAPTURE = 142;
    public static final int FRENCH_LOT = 149;
    public static final int PARAMETER_FNC3 = 151;
    public static final int MULTI_PKT_FORM = 179;
    public static final int GS1_DATAMATIRIX = 182;
    public static final int GS1_QR = 183;
    public static final int RFID_RAW = 184;
    public static final int RFID_URI = 185;

    public static String getName(int barcodeType) {
        switch (barcodeType) {
        case QRCODE: return "QR Code";
        case DATAMATRIX: return "Data Matrix";
        case EAN13: return "EAN 13";
        case EAN128: return "EAN 128";
        case EAN8: return "EAN 8";
        case AZTECCODE: return "Aztec Code";
        case PDF417: return "PDF417";
        case UPC_A: return "UPC-A";
        case UPC_E: return "UPC-E";
        case UPC_E1: return "UPC-E1";
        case BOOKLAND: return "Bookland";
        case CODE39: return "Code 39";
        case CODE93: return "Code 93";
        case CODE128: return "Code 128";
        case INTERLEAVED2OF5: return "Interleaved 2 of 5";
        case CODABAR: return "Codabar";
        case CODE11: return "Code 11";
        case MSI: return "MSI";
        case ISBT128: return "ISBT128";
        case MATRIX2OF5: return "Matrix 2 of 5";
        case MAXICODE: return "MaxiCode";
        case MICROPDF: return "Micro PDF";
        case TRIOPTIC_CODE: return "Trioptic Code";
        case DISCRETE2OF5: return "Discrete 2 of 5";
        case USPS4CB: return "USPS4CB";
        case AUSTRALIA_POST: return "Australia Post";
        case UK_POST: return "UK Post";
        case CHINESE_POST: return "Chinese Post";
        case JAPANESE_POST: return "Japanese Post";
        case NETHERLANDS_POST: return "Netherlands Post";
        case KOREAN_POST: return "Korean Post";
        case US_POSTNET: return "US Postnet";
        case US_PLANET: return "US Planet";
        case EAN_TRANSMIT_ISSN: return "EAN Transmit ISSN";
        case CODE39_FULL_ASCII: return "Code 39 Full ASCII";
        case GS1_LIMITED: return "GS1 Limited";
        case ISBT128_CONCATENATION: return "ISBT 128 Concatenation";
        case COMPOSITE_TLC_39: return "Composite TLC 39";
        case COUPON_REPORT: return "Coupon Report";
        case GS1_DATABAR_EXPANDED: return "GS1 Databar Expanded";
        case UPU_FICS_POSTAL: return "UPU Fics Postal";
        case MICROQR: return "Micro QR Code";
        case CODE49: return "Code 49";
        case OCR: return "OCR";
        case CANADIAN_POST: return "Canadian Post";
        case CODE32: return "Code 32";
        case CODE16K: return "Code 16K";
        case HANXIN: return "Han Xin";
        case IATA: return "IATA";
        case UPC_D: return "UPC-D";
        case GS1_DATABAR: return "GS1 Databar";
        case SCANLET: return "Scanlet";
        case CUECODE: return "Cue Code";
        case SIGNATURE_CAPTURE: return "Signature Capture";
        case FRENCH_LOT: return "French LOT";
        case PARAMETER_FNC3: return "Parameter FNC3";
        case MULTI_PKT_FORM: return "Multi PKT Form";
        case GS1_DATAMATIRIX: return "GS1 Datamatrix";
        case GS1_QR: return "GS1 QR Code";
        case RFID_RAW: return "RFID Raw";
        case RFID_URI: return "RFID URI";
        default: return "Unknown";
        }
    }
}
